[package]
name = "moses-analyzer"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "moses-analyzer"
path = "src/main.rs"

[dependencies]
moses-core = { path = "../core" }
moses-filesystems = { path = "../filesystems" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"